export const ROUTES = {
  MAIN: '/',
  PRICING: '/pricing',
  PRODUCTS: '/products',
  LEARN: '/learn',
  SIGN_UP: '/sign-up',
  LOGIN: '/login',
  INVITE: '/invite',
  REVIEWS: '/reviews',
  HELP: '/help',
  FAQ: '/faq',
  ACCOUNT: '/account',
  PAYMENT: '/payment',
  DASHBOARD: '/dashboard',
  INVOICES: '/invoices',
};
